"""
STUDENT CODE MAP
============================================================
FILE: backend/docx_generator.py

PURPOSE:
    Convert the text generated by the AI into a readable DOCX file.

CONNECTION:
    backend/api/document_api.py
        -> create_docx()
        -> python-docx
        -> generated/<file>.docx
        -> backend/api/downloads_api.py
        -> browser

IMPORTANT:
    Normal Markdown-like text and fenced code blocks are handled separately.
    Code indentation and '#' comments must remain unchanged.

EDIT HERE:
    Change heading levels or code font in this file.

BE CAREFUL:
    Never strip a line while it is inside a code block.
============================================================
"""

# Path safely builds the destination file path.
from pathlib import Path

# Document creates Microsoft Word (.docx) files.
from docx import Document

# All generated files use this shared project folder.
from backend.config import GENERATED_DIR


def _add_code(document, lines):
    """
    PURPOSE:
        Add one complete code block to the Word document.

    CONNECTION:
        create_docx() calls this when a fenced code block ends.

    IMPORTANT:
        Lines are written exactly as collected so Python indentation survives.
    """
    paragraph = document.add_paragraph()

    # A monospaced font makes indentation easier for students to see.
    for index, line in enumerate(lines):
        run = paragraph.add_run(line)
        run.font.name = "Courier New"
        run.font.size = 9

        # Add a real Word line break between code lines.
        if index < len(lines) - 1:
            run.add_break()


def create_docx(text, filename):
    """
    PURPOSE:
        Create one DOCX from validated AI output.

    CONNECTION:
        document_api.py calls this after validator.py accepts the output.

    INPUT:
        text     -> generated text from Qwen.
        filename -> unique output name selected by document_api.py.

    RETURNS:
        Path to the generated DOCX.

    EDIT HERE:
        Change heading levels, code font, or paragraph styles here.
    """
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    path = Path(GENERATED_DIR) / filename
    document = Document()

    code_lines = []
    in_code = False

    # Read lines in their original order.
    for raw_line in str(text).splitlines():
        # Only remove end-of-line carriage returns. Keep indentation.
        line = raw_line.rstrip("\r")

        # Fenced code markers tell us when normal text changes to code.
        if line.strip().startswith("```"):
            if in_code:
                if code_lines:
                    _add_code(document, code_lines)
                document.add_paragraph()
                code_lines = []
                in_code = False
            else:
                # Do not put ``` or ```python into the DOCX.
                in_code = True
            continue

        if in_code:
            # CRITICAL: preserve leading Python spaces.
            code_lines.append(line)
            continue

        # Ignore empty normal-text lines.
        if not line.strip():
            continue

        clean = line.strip()

        # Markdown headings are interpreted only outside code.
        if clean.startswith("### "):
            document.add_heading(clean[4:], level=3)
        elif clean.startswith("## "):
            document.add_heading(clean[3:], level=2)
        elif clean.startswith("# "):
            document.add_heading(clean[2:], level=1)
        elif clean.startswith(("- ", "* ")):
            document.add_paragraph(clean[2:], style="List Bullet")
        else:
            document.add_paragraph(clean)

    # Safely handle a missing closing fence.
    if code_lines:
        _add_code(document, code_lines)

    # Save the finished Word document.
    document.save(path)
    return path
